---
title: "Assignment 1: Bash shell tutorial and exercises"
subtitle: "Due Monday, August 31, 10 am"
format:
  pdf:
    documentclass: article
    margin-left: 30mm
    margin-right: 30mm
    toc: false
  html:
    theme: cosmo
    css: ../styles.css
    toc: false
    code-copy: true
    code-block-background: true
---

# Bash shell tutorial and exercises

Read through this [tutorial on using the bash shell](https://computing.stat.berkeley.edu/tutorial-using-bash). You can skip the pages on "Regular Expressions" and "Managing Processes", so just work on the first four pages ("Overview" through "Shell Programming"). Work through the first 10 problems in the [exercises](https://computing.stat.berkeley.edu/tutorial-using-bash/exercises) and submit your answers via Pensive. This is not a formal problem set, so you don't need to worry about formatting nor about explaining/commenting your answers, nor do you need to put your answers in your GitHub class repository. In fact it's even fine with me if you hand-write the answers and scan them to an electronic document. I just want to make sure you've worked through the tutorial. I'll be doing demonstrations on using the bash shell in class starting on August 28; this work of yours complements that.